export const theme = {
    primary: {
        color: '#6665FF',
        darkColor: '#5958E8',
        lightColor: '#5958E865',
        darkWhiteColor: '#FFFFFF',
        darkBlackColor: '#000000',
        lightTextColor: '#8B93A2',
        darkTextColor: '#484D70',
        grayColor: '#EFEFEF',
        hotPinkColor: '#FF00CC',
        checkMarkColor: '#3FB27D',
        checkOutColor: '#FF0000',
        checkinBgColor: '#ddddf8',
        lightBorderColor: '#E9E9E9',
        threeDotsColor: '#646464',
        errorTextColor: '#FF0000',
        placeholderTextColor: '#555861',
        darkBlueColor: '#303272',
        lightBlueColor: '#f5f4ff',
        slotBgColor: '#f5f5f5',
        disabledTextColor: '#9A9A9A',
        darkgrayColor: '#808080',
        darkergrayColor: '#606060',
    },
    dateSlider: {
        shiftColor: '#23C4D9',
        activeColor: '#4FCB96',
        allDaysColor: '#E5076B',
        occupiedColor: '#D9D9D9',
        daySliderItemBorderColor: '#B9B9B9',
        defaultColor: '#686868',
        editThickColor: '#777777',
        timePeriodColor: '#C0BFFF',
    },
    bottomNavigation: {
        inactiveColor: '#D8D8FF',
    },
    shiftItems: {
        activeColor: '#00BAFF',
        greyedOutColor: '#D9D9D9',
        greyedOutText: '#848484',
    },
    inputField: {
        labelColor: '#666666',
        inputBorderColor: '#C6C6C6',
    },
    cleaning: {
        checkMarkBorderColor: '#BFBFBF',
    },
    skeletonLoader: {
        backgroundColor: '#F4F4F4',
        foregroundColor: '#B5B5B5',
    },
};
